#
#Tue Mar 31 17:25:07 CVT 2026
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.password=postgres123
hibernate.connection.url=jdbc\:postgresql\://localhost\:5434/sgpsi_db
hibernate.connection.username=postgres
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
