#
#Tue Mar 17 11:41:39 CVT 2026
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.password=postgres123
hibernate.connection.url=jdbc\:postgresql\://localhost\:5434/db_vendas
hibernate.connection.username=postgres
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
