#
#Fri Mar 06 09:23:07 CVT 2026
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.password=postgres123
hibernate.connection.url=jdbc\:postgresql\://localhost\:5434/Escola
hibernate.connection.username=postgres
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
